const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_CART = "REMOVE_CART";
const CLEAR_CART = "CLEAR_CART";
const ADD_CUSTOMER = "ADD_CUSTOMER";
const ADD_SERVICE = "ADD_SERVICE";

export { ADD_TO_CART, REMOVE_CART, CLEAR_CART, ADD_CUSTOMER, ADD_SERVICE };
